# generated by fastapi-codegen:
#   filename:  ../api/openapi.yaml
#   timestamp: 2025-09-12T15:49:16+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class WaboLinksGetResponseItem(BaseModel):
    link_name: Optional[str] = Field(None, description='The name of the link.')
    length: Optional[float] = Field(
        None, description='The length of the link in millimeters.'
    )

class WaboKinematikResults(BaseModel):
    x0: float
    x1: float
    x2: float
    y0: float
    y1: float
    y2: float
    xpos: float
    ypos: float
